name:                signable
version:             0.4
github:              "coingaming/signable"
license:             BSD3
author:              "Ilja Tkachuk <tkachuk.labs@gmail.com>"
maintainer:          "Ilja Tkachuk <tkachuk.labs@gmail.com>"
copyright:           "2020 Coingaming <hello@coingaming.io>"
synopsis:            Deterministic serialisation and signatures with proto-lens support
category:            Data, Cryptography
description:         You can find documentation at <https://hackage.haskell.org/package/signable/docs/Data-Signable.html hackage>

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
# foundation
- base                  >= 4.7 && < 5
- universum             >= 1.5.0 && < 1.6
# bytes and text
- memory                >= 0.14 && < 0.16
- binary                >= 0.8.6 && < 0.9
- bytestring            >= 0.10.8 && < 0.11
- text                  >= 1.2.3 && < 1.3
- casing                >= 0.1.4 && < 0.2
# protobuf
- microlens             >= 0.4.10 && < 0.5
- proto-lens            >= 0.7.0
- proto-lens-runtime    >= 0.7.0
# crypto
- cryptonite            >= 0.25 && < 0.29
- secp256k1-haskell     >= 0.4 && < 0.6
- asn1-encoding         >= 0.9.6 && < 0.10
- asn1-types            >= 0.3 && < 0.4
- pem                   >= 0.2.4 && < 0.3

source-dirs:
- src
default-extensions:
- NoImplicitPrelude
- MultiParamTypeClasses
- LambdaCase
- OverloadedStrings
- ScopedTypeVariables
- StrictData

ghc-options:
# For details on warnings: https://downloads.haskell.org/~ghc/master/users-guide/using-warnings.html
# Enable all warnings with -Weverything, then disable the ones we don’t care about
- -Weverything
- -Werror
- -Wno-missing-exported-signatures # missing-exported-signatures turns off the more strict -Wmissing-signatures. See https://ghc.haskell.org/trac/ghc/ticket/14794#ticket
- -Wno-missing-import-lists # Requires explicit imports of _every_ function (e.g. ‘$’); too strict
- -Wno-missed-specialisations # When GHC can’t specialize a polymorphic function. No big deal and requires fixing underlying libraries to solve.
- -Wno-all-missed-specialisations # See missed-specialisations
- -Wno-unsafe # Don’t use Safe Haskell warnings
- -Wno-safe # Don’t use Safe Haskell warnings
- -Wno-missing-local-signatures # Warning for polymorphic local bindings; nothing wrong with those.
- -Wno-monomorphism-restriction # Don’t warn if the monomorphism restriction is used

library: {}

tests:
  signable-test:
    main: Spec.hs
    source-dirs:
    - test
    ghc-options:
    - -Wno-missing-export-lists # Because of generated Proto files (by proto-lens)
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - signable
    - QuickCheck            >= 2.13.2 && < 2.14
    - quickcheck-instances  >= 0.3.22 && < 0.4
    - generic-arbitrary     >= 0.1.0 && < 0.2
    - proto-lens-arbitrary  >= 0.1.2 && < 0.2
    - directory             >= 1.3 && < 1.4
    - aeson                 >= 1.4 && < 1.5
    - unordered-containers  >= 0.2 && < 0.3
    - base64-bytestring     >= 1.0 && < 1.1
    - hspec                 >= 2.7.1 && < 2.8
