name: signable-haskell-protoc
version: '0.1'
synopsis: Signable orphan instances compiler.
description: Signable orphan instances compiler.
category: Data
author: Ilja Tkachuk
maintainer: ilja@heathmont.net
github: coingaming/signable/haskell
copyright: Coingaming
license: BSD3
extra-source-files:
  - Changelog.md

executables:
  signable-haskell-protoc:
    main: main.hs
    source-dirs: src
    dependencies:
      - base
      - bytestring == 0.10.*
      - casing
      - containers >= 0.5 && < 0.7
      - ghc >= 8.2 && < 8.11
      - ghc-paths == 0.1.*
      - ghc-source-gen >= 0.4 && < 0.5
      - lens-family >= 1.2 && < 2.1
      - pretty == 1.1.*
      - proto-lens == 0.7.*
      - proto-lens-protoc == 0.7.*
      - proto-lens-runtime == 0.7.*
      - text == 1.2.*
